version: "3.2"
services:
  notification:
    build:
      context: ./services
      dockerfile: ./notification/Dockerfile
    volumes:
      - .:/app/notification
    environment:
      - SERVICE=notification
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
    env_file:
      - ./services/notification/.env
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - rabbitmq_bridge_network

  api-gateway:
    build:
      context: ./services
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app/api-gateway
    environment:
      - SERVICE=api-gateway
      - PORT=3000
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
    env_file:
      - ./services/api-gateway/.env
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_bridge_network

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=backend
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo_data:/var/lib/mongo
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
      - rabbitmq_bridge_network

volumes:
  rabbitmq_data:
  rabbitmq_log:
  mongo_data:

networks:
  rabbitmq_bridge_network:
    driver: bridge
